let data=loadData();let editDoseIndex=null;
function init(){renderDeviceChecks();renderAll();showTab("projekt");}
function showTab(id){document.querySelectorAll(".tab").forEach(t=>t.classList.add("hidden"));document.getElementById(id).classList.remove("hidden");}
function save(){storeData(data);renderAll();}
function saveProject(){data.project.name=document.getElementById("projektName").value.trim();data.project.customer=document.getElementById("kunde").value.trim();data.project.location=document.getElementById("ort").value.trim();save();}
function addRoom(){const n=document.getElementById("raumName").value.trim();if(!n)return alert("Bitte Raumname eingeben.");if(!data.rooms.includes(n))data.rooms.push(n);document.getElementById("raumName").value="";save();}
function removeRoom(room){if(!confirm("Raum löschen? Dosen bleiben erhalten."))return;data.rooms=data.rooms.filter(r=>r!==room);save();}
function renderDeviceChecks(){document.getElementById("deviceChecks").innerHTML=Object.keys(RULES).map(n=>`<label class="check"><input type="checkbox" value="${n}">${n}</label>`).join("");}
function selectedDevices(){return Array.from(document.querySelectorAll("#deviceChecks input:checked")).map(x=>x.value);}
function saveDose(){if(data.rooms.length===0)return alert("Bitte zuerst einen Raum anlegen.");const d={room:document.getElementById("doseRoom").value,name:document.getElementById("doseName").value.trim()||autoDoseName(),type:document.getElementById("doseType").value,supply:document.getElementById("supply").value,devices:selectedDevices()};if(d.devices.length===0)return alert("Bitte mindestens ein Gerät auswählen.");if(editDoseIndex===null)data.doses.push(d);else{data.doses[editDoseIndex]=d;editDoseIndex=null;}resetDoseForm();save();}
function autoDoseName(){const r=document.getElementById("doseRoom").value||"D";return r.substring(0,2).toUpperCase()+"-"+String(data.doses.length+1).padStart(2,"0");}
function editDose(i){const d=data.doses[i];editDoseIndex=i;document.getElementById("doseRoom").value=d.room;document.getElementById("doseName").value=d.name;document.getElementById("doseType").value=d.type;document.getElementById("supply").value=d.supply;document.querySelectorAll("#deviceChecks input").forEach(x=>x.checked=d.devices.includes(x.value));showTab("dosen");window.scrollTo({top:0,behavior:"smooth"});}
function deleteDose(i){if(!confirm("Dose wirklich löschen?"))return;data.doses.splice(i,1);save();}
function resetDoseForm(){editDoseIndex=null;document.getElementById("doseName").value="";document.getElementById("doseType").value="1-fach Dose";document.getElementById("supply").value="Von Verteilung";document.querySelectorAll("#deviceChecks input").forEach(x=>x.checked=false);}
function wiresForDose(d){const w=new Set();d.devices.forEach(g=>(RULES[g]||[]).forEach(l=>w.add(l)));return Array.from(w);}
function suggestion(c){if(c<=2)return"2 Einzeldrähte 1,5 mm² im Schlauch";if(c<=3)return"3 Einzeldrähte / 3×1,5";if(c<=5)return"5 Einzeldrähte / 5×1,5";if(c<=7)return"7 Einzeldrähte oder 2 Schläuche";return"Auf mehrere Schläuche aufteilen";}
function wireHtml(w){return`<div class="wire"><span class="dot ${WIRE_COLORS[w]||"violet"}"></span><span>${w}</span></div>`;}
function renderAll(){renderProject();renderRooms();renderRoomSelect();renderDoses();renderEvaluation();}
function renderProject(){document.getElementById("projektName").value=data.project.name||"";document.getElementById("kunde").value=data.project.customer||"";document.getElementById("ort").value=data.project.location||"";document.getElementById("status").innerHTML=`Gespeichert: <b>${data.project.name||"Ohne Namen"}</b><br>Räume: ${data.rooms.length} · Dosen: ${data.doses.length}`;}
function renderRooms(){const el=document.getElementById("roomList");if(!data.rooms.length){el.innerHTML="Noch keine Räume.";return;}el.innerHTML=data.rooms.map(r=>`<div class="item"><b>${r}</b><br>${data.doses.filter(d=>d.room===r).length} Dosen<button class="danger" onclick="removeRoom('${r.replaceAll("'","\\'")}')">Löschen</button></div>`).join("");}
function renderRoomSelect(){document.getElementById("doseRoom").innerHTML=data.rooms.map(r=>`<option>${r}</option>`).join("");}
function renderDoses(){const el=document.getElementById("doseList");if(!data.doses.length){el.innerHTML="Noch keine Dosen.";return;}el.innerHTML=data.doses.map((d,i)=>`<div class="item"><b>${d.name}</b> (${d.room})<br>${d.type} · ${d.supply}<br>${d.devices.map(g=>`<span class="pill">${g}</span>`).join("")}<button class="secondary" onclick="editDose(${i})">Ändern</button><button class="danger" onclick="deleteDose(${i})">Löschen</button></div>`).join("");}
function renderEvaluation(){const we=document.getElementById("wireList"),ma=document.getElementById("materialList");if(!data.doses.length){we.innerHTML="Noch keine Dosen.";ma.innerHTML="Noch keine Dosen.";return;}we.innerHTML=data.doses.map(d=>{const w=wiresForDose(d);return`<div class="item"><b>${d.name}</b> (${d.room})<br>${w.map(wireHtml).join("")}<b>${w.length} Drähte</b><br>Vorschlag: ${suggestion(w.length)}</div>`;}).join("");const gc={},dc={};data.doses.forEach(d=>{dc[d.type]=(dc[d.type]||0)+1;d.devices.forEach(g=>gc[g]=(gc[g]||0)+1);});ma.innerHTML=`<h3>Dosenarten</h3>${Object.entries(dc).map(([k,v])=>`<div>${v} × ${k}</div>`).join("")}<h3>Geräte</h3>${Object.entries(gc).map(([k,v])=>`<div>${v} × ${k}</div>`).join("")}<h3>Übersicht</h3><table><tr><th>Dose</th><th>Raum</th><th>Drähte</th><th>Vorschlag</th></tr>${data.doses.map(d=>{const c=wiresForDose(d).length;return`<tr><td>${d.name}</td><td>${d.room}</td><td>${c}</td><td>${suggestion(c)}</td></tr>`;}).join("")}</table>`;}
function loadExample(){data={project:{name:"Testprojekt",customer:"",location:"Österreich",country:"Österreich"},rooms:["Wohnzimmer","Küche"],doses:[{room:"Wohnzimmer",name:"WZ-01",type:"2-fach Dose",supply:"Von Verteilung",devices:["Steckdose","Schalter"]},{room:"Wohnzimmer",name:"WZ-02",type:"1-fach Dose",supply:"Von Verteilung",devices:["Wechselschalter erster"]},{room:"Wohnzimmer",name:"WZ-03",type:"1-fach Dose",supply:"Von Verteilung",devices:["Wechselschalter letzter"]},{room:"Wohnzimmer",name:"L-01",type:"Lampenauslass",supply:"Von Verteilung",devices:["Lampe"]}]};save();}
function clearAll(){if(!confirm("Alles löschen?"))return;data=defaultData();save();}
init();
